version: '3'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BloombergDataWarehouseLiveDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password



#version: '3.1'
#services:
#  app:
#    container_name: clusteredDataWarehouse
#    image: clustereddatawarehouse
#    build: ./
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    networks:
#      - network
#  db:
#    container_name: clusteredData_Warehouse
#    image: postgres:latest
#    ports:
#      - "5433:5432"
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=BloombergDataWarehouse
#    networks:
#      - network
#
#networks:
#  network:
#    driver: bridge
